import express from 'express'
import cors from 'cors'
import { createHash, randomBytes, randomInt, scryptSync, timingSafeEqual } from 'node:crypto'
import { db, row, rows, transaction } from './db.js'

const app = express()
const port = Number(process.env.PORT || 3001)
app.use(cors({ origin: process.env.CORS_ORIGIN?.split(',') || 'http://localhost:5173' }))
app.use(express.json({ limit: '1mb' }))
class HttpError extends Error { constructor(status, message) { super(message); this.status = status } }
const fail = (status, message) => { throw new HttpError(status, message) }
const positiveId = v => Number.isInteger(Number(v)) && Number(v) > 0
const hash = value => createHash('sha256').update(value).digest('hex')
const passwordHash = password => { const salt=randomBytes(16).toString('hex'); return `${salt}:${scryptSync(password,salt,64).toString('hex')}` }
const passwordMatches = (password, stored) => { const [salt,key]=stored.split(':'); const actual=scryptSync(password,salt,64); return timingSafeEqual(actual,Buffer.from(key,'hex')) }
const emailOkay = value => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value||'')
const makeSession = userId => { const token=randomBytes(32).toString('base64url'); db.prepare("INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(?,?,datetime('now','+7 days'))").run(userId,hash(token)); return token }
const currentUser = req => { const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,''); if(!token) return null; return row("SELECT u.id,u.name,u.email,u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP",hash(token)) }
function getId(table, id, label) { if (!positiveId(id)) fail(400, `Invalid ${label} id`); const item = row(`SELECT * FROM ${table} WHERE id=?`, Number(id)); if (!item) fail(404, `${label} not found`); return item }
function validBody(body) { if (!body || typeof body !== 'object' || Array.isArray(body)) fail(400, 'Request body must be a JSON object') }
function listFilters(query) {
  const clauses=[], params=[]
  for (const [key,col] of [['status','o.status'],['type','o.type']]) if(query[key]) { clauses.push(`${col}=?`); params.push(query[key].toUpperCase()) }
  for (const [key,col] of [['productId','l.product_id'],['warehouseId','w.id'],['locationId','l.destination_location_id']]) if(query[key]) { clauses.push(`${col}=?`); params.push(Number(query[key])) }
  if(query.search) { clauses.push('(o.reference LIKE ? OR o.supplier_customer LIKE ? OR p.name LIKE ? OR p.sku LIKE ?)'); params.push(...Array(4).fill(`%${query.search}%`)) }
  return { where:clauses.length ? `WHERE ${clauses.join(' AND ')}` : '', params }
}
function operationDetail(id) { const o=getId('operations',id,'Operation'); return {...o, lines:rows('SELECT l.*,p.name product_name,p.sku,sl.name source_location,dl.name destination_location FROM operation_lines l JOIN products p ON p.id=l.product_id LEFT JOIN locations sl ON sl.id=l.source_location_id LEFT JOIN locations dl ON dl.id=l.destination_location_id WHERE l.operation_id=?',o.id)} }
app.get('/api/health', (_req,res)=>res.json({success:true,data:{status:'ok'}}))
app.post('/api/auth/signup',(req,res)=>{validBody(req.body);const name=req.body.name?.trim(),email=req.body.email?.trim().toLowerCase(),password=req.body.password;if(!name||!emailOkay(email)||typeof password!=='string'||password.length<8)fail(400,'Enter a name, valid email, and password of at least 8 characters');const id=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run(name,email,passwordHash(password)).lastInsertRowid;const user=getId('users',id,'User');const token=makeSession(user.id);res.status(201).json({success:true,data:{user:{id:user.id,name:user.name,email:user.email},token}})})
app.post('/api/auth/login',(req,res)=>{validBody(req.body);const user=row('SELECT * FROM users WHERE email=? COLLATE NOCASE',req.body.email?.trim());if(!user||!passwordMatches(req.body.password||'',user.password_hash))fail(401,'Email or password is incorrect');const token=makeSession(user.id);res.json({success:true,data:{user:{id:user.id,name:user.name,email:user.email},token}})})
app.get('/api/auth/me',(req,res)=>{const user=currentUser(req);if(!user)fail(401,'Authentication required');res.json({success:true,data:{user}})})
app.post('/api/auth/logout',(req,res)=>{const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(token)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(token));res.json({success:true,data:{loggedOut:true}})})
app.post('/api/auth/request-password-reset',(req,res)=>{validBody(req.body);const user=row('SELECT * FROM users WHERE email=? COLLATE NOCASE',req.body.email?.trim());if(!user)fail(404,'No account exists for that email');const otp=String(randomInt(100000,1000000));db.prepare("INSERT INTO password_resets(user_id,otp_hash,expires_at) VALUES(?,?,datetime('now','+10 minutes'))").run(user.id,hash(otp));console.log(`[DEV ONLY] Password reset OTP for ${user.email}: ${otp}`);res.json({success:true,data:{message:'Development OTP generated',...(process.env.NODE_ENV==='production'?{}:{devOtp:otp})}})})
app.post('/api/auth/verify-otp',(req,res)=>{validBody(req.body);const user=row('SELECT id FROM users WHERE email=? COLLATE NOCASE',req.body.email?.trim());const reset=user&&row('SELECT * FROM password_resets WHERE user_id=? AND otp_hash=? AND expires_at>CURRENT_TIMESTAMP ORDER BY id DESC LIMIT 1',user.id,hash(String(req.body.otp||'')));if(!reset)fail(400,'Invalid or expired OTP');db.prepare('UPDATE password_resets SET verified=1 WHERE id=?').run(reset.id);res.json({success:true,data:{verified:true}})})
app.post('/api/auth/reset-password',(req,res)=>{validBody(req.body);const user=row('SELECT id FROM users WHERE email=? COLLATE NOCASE',req.body.email?.trim());const reset=user&&row('SELECT * FROM password_resets WHERE user_id=? AND verified=1 AND expires_at>CURRENT_TIMESTAMP ORDER BY id DESC LIMIT 1',user.id);if(!reset||!timingSafeEqual(Buffer.from(reset.otp_hash),Buffer.from(hash(String(req.body.otp||'')))))fail(400,'Verify a valid OTP first');if(typeof req.body.password!=='string'||req.body.password.length<8)fail(400,'Password must be at least 8 characters');db.prepare('UPDATE users SET password_hash=? WHERE id=?').run(passwordHash(req.body.password),user.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(user.id);db.prepare('DELETE FROM password_resets WHERE user_id=?').run(user.id);res.json({success:true,data:{reset:true}})})
app.get('/api/categories',(_req,res)=>res.json({success:true,data:rows('SELECT * FROM categories ORDER BY name')}))
app.post('/api/categories',(req,res)=>{validBody(req.body); if(!req.body.name?.trim()) fail(400,'name is required'); const r=db.prepare('INSERT INTO categories(name) VALUES(?)').run(req.body.name.trim()); res.status(201).json({success:true,data:getId('categories',r.lastInsertRowid,'Category')})})
app.get('/api/warehouses',(_req,res)=>res.json({success:true,data:rows('SELECT * FROM warehouses ORDER BY name')}))
app.post('/api/warehouses',(req,res)=>{validBody(req.body); if(!req.body.name?.trim()||!req.body.code?.trim()) fail(400,'name and code are required'); const r=db.prepare('INSERT INTO warehouses(name,code) VALUES(?,?)').run(req.body.name.trim(),req.body.code.trim());res.status(201).json({success:true,data:getId('warehouses',r.lastInsertRowid,'Warehouse')})})
app.get('/api/locations',(req,res)=>res.json({success:true,data:rows('SELECT l.*,w.name warehouse_name FROM locations l JOIN warehouses w ON w.id=l.warehouse_id WHERE (? IS NULL OR w.id=?) ORDER BY w.name,l.name',req.query.warehouseId||null,req.query.warehouseId||null)}))
app.post('/api/locations',(req,res)=>{validBody(req.body); getId('warehouses',req.body.warehouse_id,'Warehouse'); if(!req.body.name?.trim()||!req.body.code?.trim()) fail(400,'name and code are required'); const r=db.prepare('INSERT INTO locations(warehouse_id,name,code) VALUES(?,?,?)').run(req.body.warehouse_id,req.body.name.trim(),req.body.code.trim());res.status(201).json({success:true,data:getId('locations',r.lastInsertRowid,'Location')})})
app.get('/api/products',(req,res)=>res.json({success:true,data:rows(`SELECT p.*,c.name category,COALESCE(SUM(b.quantity),0) stock FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN stock_balances b ON b.product_id=p.id WHERE (? IS NULL OR p.active=?) GROUP BY p.id ORDER BY p.name`,req.query.active===undefined?null:Number(req.query.active),req.query.active===undefined?null:Number(req.query.active))}))
app.post('/api/products',(req,res)=>{validBody(req.body); if(!req.body.name?.trim()||!req.body.sku?.trim()) fail(400,'name and sku are required'); if(req.body.category_id) getId('categories',req.body.category_id,'Category'); const reorder=Number(req.body.reorder_level||0);if(!Number.isFinite(reorder)||reorder<0)fail(400,'reorder_level must be non-negative');const r=db.prepare('INSERT INTO products(name,sku,category_id,uom,reorder_level) VALUES(?,?,?,?,?)').run(req.body.name.trim(),req.body.sku.trim(),req.body.category_id||null,req.body.uom||'units',reorder);res.status(201).json({success:true,data:getId('products',r.lastInsertRowid,'Product')})})
app.get('/api/products/:id',(req,res)=>res.json({success:true,data:{...getId('products',req.params.id,'Product'),stock:rows('SELECT b.*,l.name location,w.name warehouse FROM stock_balances b JOIN locations l ON l.id=b.location_id JOIN warehouses w ON w.id=l.warehouse_id WHERE b.product_id=?',Number(req.params.id))}}))
app.put('/api/products/:id',(req,res)=>{const p=getId('products',req.params.id,'Product');validBody(req.body);const name=req.body.name??p.name,sku=req.body.sku??p.sku,cat=req.body.category_id===undefined?p.category_id:req.body.category_id;if(cat)getId('categories',cat,'Category');db.prepare('UPDATE products SET name=?,sku=?,category_id=?,uom=?,reorder_level=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(name,sku,cat,req.body.uom??p.uom,req.body.reorder_level??p.reorder_level,req.body.active===undefined?p.active:Number(Boolean(req.body.active)),p.id);res.json({success:true,data:getId('products',p.id,'Product')})})
function createOperation(type,req,res){validBody(req.body);const input=req.body;if(!Array.isArray(input.lines)||!input.lines.length)fail(400,'At least one product line is required');if(['RECEIPT'].includes(type)&&!input.supplier)fail(400,'supplier is required');if(['DELIVERY'].includes(type)&&!input.customer)fail(400,'customer is required');const source=input.source_location_id??null,dest=input.destination_location_id??null;if(source)getId('locations',source,'Source location');if(dest)getId('locations',dest,'Destination location');if(type==='TRANSFER'&&(!source||!dest||Number(source)===Number(dest)))fail(400,'Transfer requires different source and destination locations');if(type==='RECEIPT'&&!dest)fail(400,'Receipt destination location is required');if(type==='DELIVERY'&&!source)fail(400,'Delivery source location is required');if(type==='ADJUSTMENT'&&!dest&&!source)fail(400,'Adjustment location is required');const ref=input.reference?.trim()||`${type.slice(0,3)}-${Date.now()}`;const opId=transaction(()=>{const op=db.prepare('INSERT INTO operations(reference,type,status,supplier_customer,source_location_id,destination_location_id) VALUES(?,?,?, ?,?,?)').run(ref,type,input.status==='READY'?'READY':'DRAFT',input.supplier||input.customer||null,source,dest).lastInsertRowid;for(const l of input.lines){getId('products',l.product_id,'Product');const counted=type==='ADJUSTMENT'?Number(l.counted_quantity):null;const q=type==='ADJUSTMENT'?1:Number(l.quantity);if(type==='ADJUSTMENT'&&(!Number.isFinite(counted)||counted<0))fail(400,'Adjustment counted_quantity must be non-negative');if(type!=='ADJUSTMENT'&&(!Number.isFinite(q)||q<=0))fail(400,'Line quantities must be greater than zero');const lineSource=l.source_location_id??source,lineDest=l.destination_location_id??dest;if(lineSource)getId('locations',lineSource,'Source location');if(lineDest)getId('locations',lineDest,'Destination location');if(type==='TRANSFER'&&Number(lineSource)===Number(lineDest))fail(400,'Transfer locations must be different');if(type==='ADJUSTMENT'&&!lineSource&&!lineDest)fail(400,'Adjustment location is required');db.prepare('INSERT INTO operation_lines(operation_id,product_id,quantity,counted_quantity,source_location_id,destination_location_id) VALUES(?,?,?,?,?,?)').run(op,l.product_id,q,type==='ADJUSTMENT'?counted:null,lineSource,lineDest)}return op});res.status(201).json({success:true,data:operationDetail(opId)})}
for(const [plural,type] of [['receipts','RECEIPT'],['deliveries','DELIVERY'],['transfers','TRANSFER'],['adjustments','ADJUSTMENT']]){app.get(`/api/${plural}`,(req,res)=>{const {where,params}=listFilters(req.query);res.json({success:true,data:rows(`SELECT DISTINCT o.* FROM operations o LEFT JOIN operation_lines l ON l.operation_id=o.id LEFT JOIN products p ON p.id=l.product_id LEFT JOIN locations dl ON dl.id=COALESCE(l.destination_location_id,o.destination_location_id) LEFT JOIN warehouses w ON w.id=dl.warehouse_id ${where} ${where?'AND':'WHERE'} o.type=? ORDER BY o.created_at DESC`,...params,type).map(o=>operationDetail(o.id))})});app.post(`/api/${plural}`,(req,res)=>createOperation(type,req,res));app.get(`/api/${plural}/:id`,(req,res)=>{const o=operationDetail(req.params.id);if(o.type!==type)fail(404,'Operation not found');res.json({success:true,data:o})});app.post(`/api/${plural}/:id/validate`,(req,res)=>res.json({success:true,data:validateOperation(req.params.id,type)}));app.post(`/api/${plural}/:id/cancel`,(req,res)=>res.json({success:true,data:cancelOperation(req.params.id,type)}))}
function validateOperation(id,type){return transaction(()=>{const o=getId('operations',id,'Operation');if(o.type!==type)fail(404,'Operation not found');if(o.status==='DONE')fail(409,'Operation is already validated');if(o.status==='CANCELED')fail(409,'Canceled operation cannot be validated');const lines=rows('SELECT * FROM operation_lines WHERE operation_id=?',o.id);if(!lines.length)fail(400,'Operation has no lines');for(const l of lines){const source=l.source_location_id??o.source_location_id,dest=l.destination_location_id??o.destination_location_id;let movements=[];if(type==='RECEIPT')movements=[[dest,l.quantity]];if(type==='DELIVERY')movements=[[source,-l.quantity]];if(type==='TRANSFER')movements=[[source,-l.quantity],[dest,l.quantity]];if(type==='ADJUSTMENT'){const loc=dest??source;const before=row('SELECT quantity FROM stock_balances WHERE product_id=? AND location_id=?',l.product_id,loc)?.quantity||0;movements=[[loc,l.counted_quantity-before]]}for(const [loc,delta] of movements){if(!loc)fail(400,'Operation location is required');getId('locations',loc,'Location');const before=row('SELECT quantity FROM stock_balances WHERE product_id=? AND location_id=?',l.product_id,loc)?.quantity||0;const after=before+delta;if(after < -1e-9)fail(409,'Insufficient stock');db.prepare('INSERT INTO stock_balances(product_id,location_id,quantity) VALUES(?,?,?) ON CONFLICT(product_id,location_id) DO UPDATE SET quantity=excluded.quantity').run(l.product_id,loc,Math.max(0,after));db.prepare('INSERT INTO stock_ledger(operation_id,operation_type,reference,product_id,quantity_delta,source_location_id,destination_location_id,previous_quantity,resulting_quantity) VALUES(?,?,?,?,?,?,?,?,?)').run(o.id,type,o.reference,l.product_id,delta,type==='RECEIPT'?null:source,type==='DELIVERY'?null:dest,before,Math.max(0,after))}}db.prepare("UPDATE operations SET status='DONE',validated_at=CURRENT_TIMESTAMP WHERE id=?").run(o.id);return operationDetail(o.id)})}
function cancelOperation(id,type){return transaction(()=>{const o=getId('operations',id,'Operation');if(o.type!==type)fail(404,'Operation not found');if(o.status==='DONE')fail(409,'Validated operation cannot be canceled');if(o.status==='CANCELED')fail(409,'Operation is already canceled');db.prepare("UPDATE operations SET status='CANCELED' WHERE id=?").run(o.id);return operationDetail(o.id)})}
app.get('/api/ledger',(req,res)=>{const clauses=[],params=[];for(const [key,col] of [['type','l.operation_type'],['productId','l.product_id'],['locationId','COALESCE(l.destination_location_id,l.source_location_id)'],['warehouseId','w.id']])if(req.query[key]){clauses.push(`${col}=?`);params.push(key==='type'?req.query[key].toUpperCase():Number(req.query[key]))}if(req.query.search){clauses.push('(l.reference LIKE ? OR p.name LIKE ? OR p.sku LIKE ?)');params.push(...Array(3).fill(`%${req.query.search}%`))}const sql=`SELECT l.*,p.name product_name,p.sku,sl.name source_location,dl.name destination_location FROM stock_ledger l JOIN products p ON p.id=l.product_id LEFT JOIN locations dl ON dl.id=l.destination_location_id LEFT JOIN locations sl ON sl.id=l.source_location_id LEFT JOIN warehouses w ON w.id=COALESCE(dl.warehouse_id,sl.warehouse_id) ${clauses.length?'WHERE '+clauses.join(' AND '):''} ORDER BY l.id DESC`;res.json({success:true,data:rows(sql,...params)})})
app.get('/api/moves',(req,res)=>res.json({success:true,data:rows("SELECT o.*,COUNT(DISTINCT l.product_id) product_count,COUNT(sl.id) ledger_entries FROM operations o LEFT JOIN operation_lines l ON l.operation_id=o.id LEFT JOIN stock_ledger sl ON sl.operation_id=o.id GROUP BY o.id ORDER BY o.id DESC")}))
app.get('/api/dashboard',(_req,res)=>{
  const products=rows('SELECT p.id,p.name,p.sku,p.reorder_level,COALESCE(SUM(b.quantity),0) stock FROM products p LEFT JOIN stock_balances b ON b.product_id=p.id WHERE p.active=1 GROUP BY p.id')
  const low=products.filter(p=>p.stock<=p.reorder_level)
  const operations=rows('SELECT o.*,GROUP_CONCAT(DISTINCT p.name) product_names,SUM(l.quantity) total_quantity,GROUP_CONCAT(DISTINCT loc.name) location_names FROM operations o LEFT JOIN operation_lines l ON l.operation_id=o.id LEFT JOIN products p ON p.id=l.product_id LEFT JOIN locations loc ON loc.id=COALESCE(l.destination_location_id,l.source_location_id,o.destination_location_id,o.source_location_id) GROUP BY o.id ORDER BY o.created_at DESC LIMIT 8')
  const pending=type=>row("SELECT COUNT(*) n FROM operations WHERE type=? AND status IN ('DRAFT','READY')",type).n
  res.json({success:true,data:{totalProductsInStock:products.filter(p=>p.stock>0).length,lowStockCount:low.length,outOfStockCount:products.filter(p=>p.stock<=0).length,pendingReceipts:pending('RECEIPT'),pendingDeliveries:pending('DELIVERY'),scheduledTransfers:pending('TRANSFER'),lowStockProducts:low,recentOperations:operations,stockByLocation:rows('SELECT w.name warehouse,l.id location_id,l.name location,SUM(b.quantity) quantity FROM stock_balances b JOIN locations l ON l.id=b.location_id JOIN warehouses w ON w.id=l.warehouse_id GROUP BY l.id ORDER BY w.name,l.name')}})
})
app.use((err,_req,res,_next)=>{const status=err.status||(err.code==='SQLITE_CONSTRAINT_UNIQUE'||err.code==='SQLITE_CONSTRAINT_PRIMARYKEY'?409:400);res.status(status).json({success:false,error:{message:status===500?'Internal server error':err.message}})})
app.listen(port,()=>console.log(`StockSense API listening on http://localhost:${port}`))
